package io.github.teamcheeze.remoteActions.server;

import java.awt.event.KeyEvent;

public enum KeyboardKeys {
    A(KeyEvent.VK_A),
    B(KeyEvent.VK_B),
    C(KeyEvent.VK_C),
    D(KeyEvent.VK_D),
    E(KeyEvent.VK_E),
    F(KeyEvent.VK_F),
    G(KeyEvent.VK_G),
    H(KeyEvent.VK_H),
    I(KeyEvent.VK_I),
    J(KeyEvent.VK_J),
    K(KeyEvent.VK_K),
    L(KeyEvent.VK_L),
    M(KeyEvent.VK_M),
    N(KeyEvent.VK_N),
    O(KeyEvent.VK_O),
    P(KeyEvent.VK_P),
    Q(KeyEvent.VK_Q),
    R(KeyEvent.VK_R),
    S(KeyEvent.VK_S),
    T(KeyEvent.VK_T),
    U(KeyEvent.VK_U),
    V(KeyEvent.VK_V),
    W(KeyEvent.VK_W),
    X(KeyEvent.VK_X),
    Y(KeyEvent.VK_Y),
    Z(KeyEvent.VK_Z),
    ESC(KeyEvent.VK_ESCAPE),
    F1(KeyEvent.VK_F1),
    F2(KeyEvent.VK_F2),
    F3(KeyEvent.VK_F3),
    F4(KeyEvent.VK_F4),
    F5(KeyEvent.VK_F5),
    F6(KeyEvent.VK_F6),
    F7(KeyEvent.VK_F7),
    F8(KeyEvent.VK_F8),
    F9(KeyEvent.VK_F9),
    F10(KeyEvent.VK_F10),
    F11(KeyEvent.VK_F11),
    F12(KeyEvent.VK_F12),
    FN_LOCK(KeyEvent.VK_PRINTSCREEN),
    INSERT(KeyEvent.VK_INSERT),
    DEL(KeyEvent.VK_DELETE),
    ONE(KeyEvent.VK_1),
    TWO(KeyEvent.VK_2),
    THREE(KeyEvent.VK_3),
    FOUR(KeyEvent.VK_4),
    FIVE(KeyEvent.VK_5),
    SIX(KeyEvent.VK_6),
    SEVEN(KeyEvent.VK_7),
    EIGHT(KeyEvent.VK_8),
    NINE(KeyEvent.VK_9),
    ZERO(KeyEvent.VK_0),
    MINUS(KeyEvent.VK_MINUS),
    PLUS(KeyEvent.VK_PLUS),
    BACKSPACE(KeyEvent.VK_BACK_SPACE),
    TAB(KeyEvent.VK_TAB),
    CAPS_LOCK(KeyEvent.VK_CAPS_LOCK),
    SHIFT(KeyEvent.VK_SHIFT),
    CTRL(KeyEvent.VK_CONTROL),
    WINDOWS(KeyEvent.VK_WINDOWS),
    ALT(KeyEvent.VK_ALT),
    SPACE(KeyEvent.VK_SPACE),
    ARROW_LEFT(KeyEvent.VK_LEFT),
    ARROW_TOP(KeyEvent.VK_UP),
    ARROW_DOWN(KeyEvent.VK_DOWN),
    ARROW_RIGHT(KeyEvent.VK_RIGHT),
    ENTER(KeyEvent.VK_ENTER),
    COMMA(KeyEvent.VK_COMMA),
    PERIOD(KeyEvent.VK_PERIOD),
    SLASH(KeyEvent.VK_SLASH),
    COLON(KeyEvent.VK_COLON),
    QUOTES(KeyEvent.VK_QUOTE),
    DOUBLE_QUOTES(KeyEvent.VK_QUOTEDBL),
    BRACES_OPEN(KeyEvent.VK_BRACELEFT),
    BRACES_CLOSE(KeyEvent.VK_BRACERIGHT);
    private final int keycode;
    KeyboardKeys(int keycode) {
        this.keycode = keycode;
    }

    public int getKeycode() {
        return keycode;
    }
}
